name: Run CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 5 * * *'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      ## download the source
      - name: Checkout
        uses: actions/checkout@v3

      ## setup node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      ## install dependencies (this has caching)
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test and Upload
        uses: replayio/action-playwright@v0.4.10
        with:
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
          public: true
          upload-all: true